### ISSUE TITLE
java error in project app

### ISSUE THREAD

**Issue by torokris** [zendesklabs/project_app#15]
Hello, I'm testing the Project App in my Zendesk. I'm very satisfied with the app. I have i in the last weeks or so had a error on Zendesk. Se attaced file. 

![java_error](https://cloud.githubusercontent.com/assets/11550801/6725409/51a862b8-ce09-11e4-8806-eb02c9ae2c63.jpg)

**Comment by skipjac** [comment]
@torokris what plan are you on? Also did you enable Brands or ticket forms?

**Comment by torokris** [comment]
I'm on the Free Plan on GitHub if that is what Your question means. How do I enable Brands or ticket forms?

**Comment by skipjac** [comment]
Try downloading the zip file from the repo it has some updates.
