### ISSUE TITLE
framework exception

### ISSUE THREAD

**Issue by edalsted** [zendesklabs/project_app#19]
Occasionally, when browsing to a parent or child ticket the following exception is observed:

![image](https://cloud.githubusercontent.com/assets/6535584/11904884/b7b3dc2a-a588-11e5-8f51-1fa478338beb.png)

**Comment by skipjac** [comment]
How often does this happen? And is it only on tickets within a project?

**Comment by skipjac** [comment]
A fix has been found and will be published soon

**Comment by skipjac** [comment]
Fix has been deployed
