### ISSUE TITLE
Form fields not pulling over into Project App

### ISSUE THREAD

**Issue by Jessfrantz** [zendesklabs/project_app#31]
The fields from our Zendesk Forms aren't pulling into the Project App on our site.  We only get the following fields, regardless of which form we choose:

-Ticket Form
-Requester
-Group
-Assignee Name
-Ticket Type
-Subject
-Description

One of our forms has about 40 fields, and they were all pulling into Project App through yesterday evening-- all of a sudden this morning we're only getting the 6 fields above.

Thank you!

**Comment by skipjac** [comment]
Are there any errors in the browser console?

**Comment by skipjac** [comment]
It looks like there was a change to the Zendesk framework yesterday. I am reaching out to the dev relationship manager trying to figure what is going on

**Comment by skipjac** [comment]
This has been fixed by Zendesk
