### ISSUE TITLE
New Release 9/Jan/2018 

### ISSUE THREAD

**Issue by damianwi** [zendesklabs/project_app#43]
We noticed that something changed in Zendesk regarding creating new child tickets. In the form there are less fields to be filled in (which were important for us).

**Comment by skipjac** [comment]
can you post a screen shot?

**Comment by mr-mark** [comment]
hey we experienced the same issue,

Screenshots attached. Old project is how it used to look which worked fine for us, and new project single which doesnt work.

![old project single](https://user-images.githubusercontent.com/35313786/34798791-82bac188-f6b1-11e7-89c1-4ad5615bbf28.png)
![new project single](https://user-images.githubusercontent.com/35313786/34798795-873f1af6-f6b1-11e7-92e9-d07cc000dc9c.png)

**Comment by mr-mark** [comment]
This is how it used to look which it used and the fields would be populated using the data from the parent ticket.

![old project single](https://user-images.githubusercontent.com/35313786/34798899-d2b6e180-f6b1-11e7-8527-a52865a2a7b9.png)

This is how it now looks, no fields copied over and no where near the same amount.
![new project single](https://user-images.githubusercontent.com/35313786/34798907-db3f6480-f6b1-11e7-828a-4f66d789653b.png)

**Comment by skipjac** [comment]
Ok this is a issue with people who don't have ticket forms. Sorry total miss on my end working on it right now.

**Comment by bminick** [comment]
This was a issue we had as well and we do use multiple ticket forms. We were able to fix it by clicking create bulk, then create single. That seemed to bring the fields back.

**Comment by skipjac** [comment]
I did a push about a hour ago let me know if you are seeing issues.

**Comment by damianwi** [comment]
Looks much better.
Many thanks for the quick response!
