### ISSUE TITLE
Parent ticket not being included in project

### ISSUE THREAD

**Issue by airloeb** [zendesklabs/project_app#49]
Every couple of projects the parent ticket is not getting included or linked to the project. Screenshots posted below

Ticket 18624 (parent ticket) showing as not in a project
![image](https://user-images.githubusercontent.com/11204920/36231110-d1fbb748-11aa-11e8-906b-99b1440405db.png)
Correct tags are set
![qualitybath - agent 2018-02-14 17-17-02](https://user-images.githubusercontent.com/11204920/36231126-e0aace6e-11aa-11e8-844b-91b23c78e1cd.png)
Custom Field is set
![image](https://user-images.githubusercontent.com/11204920/36231139-ee7ee6a6-11aa-11e8-83f1-35606b0c85ae.png)

--------------

Ticket 18632 (child ticket) showing as in project without parent
![qualitybath - agent 2018-02-14 17-20-13](https://user-images.githubusercontent.com/11204920/36231244-5ad975fa-11ab-11e8-96b8-36673f659b80.png)
![qualitybath - agent 2018-02-14 17-20-38](https://user-images.githubusercontent.com/11204920/36231252-61bcea46-11ab-11e8-99df-1328587fecb0.png)

**Comment by skipjac** [comment]
Thanks I will try and reproduce this

**Comment by skipjac** [comment]
I have pushed a fix for this to the market place
