### ISSUE TITLE
Project Management app is not loading for customer instance

### ISSUE THREAD

**Issue by saundishah** [zendesklabs/project_app#50]
I am logging this issue on behalf of the customer - getaroom. The app is not loading anymore in their instance. They have already tried with different users and everyone is seeing the same issue. They also tried clearing the cache/cookies and rebooting their computers but no luck.

Here is a screenshot of what the app interface looks like:

![image](https://user-images.githubusercontent.com/36669217/36432158-1cc23608-161f-11e8-9ad1-23e6854102fc.png)

They have been using this app for a long time without any issues and its now become an integral part of what they do. They need to find a resolution quickly. Any assistance here would be appreciated.

**Comment by skipjac** [comment]
Hi did they get it from the app market place or were given a zip to upload?

**Comment by skipjac** [comment]
I haven't heard back from you.
