### ISSUE TITLE
Project Management app -  Parent ticket solved with open child

### ISSUE THREAD

**Issue by Dls1dls1** [zendesklabs/project_app#68]
When using Project Management app, should I be able to Solve a parent ticket that has an open child ticket?   My system allowed me to do this. Should it have or do I have something not setup correctly?

**Comment by jlobaton** [comment]
I have the same problem, could you solve it?

**Comment by skipjac** [comment]
This app has been taken over by the Zendesk team. I will pass on the issue.

**Comment by jlobaton** [comment]
ok thanks, but when will the app be available? why is it not on the zendesk marketplace

**Comment by jlobaton** [comment]
I don't know if it is a problem, but when the child ticket is assigned to a group, the parent ticket cannot be solved, but when the child ticket is assigned to an agent, the parent ticket can be solved, I thought that it did not allow solving the parent ticket until the child ticket was resolved

**Comment by jlobaton** [comment]
> This app has been taken over by the Zendesk team. I will pass on the issue.

ok thanks, but when will the app be available? why is it not on the zendesk marketplace

**Comment by skipjac** [comment]
They will look at this issue and we are hoping in the next month
