### ISSUE TITLE
Child ticket

### ISSUE THREAD

**Issue by ErenS123** [zendesklabs/project_app#69]
Hi, 

We are experiencing issues with our agents not being able to view the children on the child ticket app.  We create a child ticket, but we are not able to view the ticket immediately after it is created or at all.  

The other issue is multiple ticket children tickets being created after clicking on create a single ticket to submit the child ticket.

**Comment by skipjac** [comment]
Unfortunately, due to limitations of Zendesk the app was changed to use a
different api end point for look up and it can now take up to 2 minutes for
new child tickets to show up.

**Comment by ErenS123** [comment]
Hello,

It is actually taking longer than 2 minutes for the child ticket to load.  We are not able to view the child tickets until more than 2 days later.  

Also, what about the duplication of child tickets?
