### ISSUE TITLE
Child tickets progress

### ISSUE THREAD

**Issue by Ahmedtapl** [zendesklabs/project_app#71]
Is there anyway I could assign a trigger to change a custom field on the parent ticket based on specific child ticket status.

Scenario:
Parent ticket has two child tickets.

If 1st Child ticket is not "Open",
2nd Child ticket is not "Open"

Then

Parent ticket "Custom field" to change whatever the value is.

The benefit is to track the Parent ticket instead of checking them manually to take action on the parent ticket.

**Comment by Ahmedtapl** [comment]
Updates?

**Comment by skipjac** [comment]
There is a new team working on this app to make it part of the official Zendesk App Market. Any new features will be handled by them.
